### ISSUE TITLE
BUG: on npm 2 `builder postinstall` fails if builder package includes another builder package

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/builder-react-component#12]
Not sure whether this is an issue with the archetype or builder itself...

on repos that are using builder,`npm install` will fail if they include another package that uses builder. 

failing CI on this repo is an example
https://github.com/FormidableLabs/victory-axis/pull/40

**Comment by ryan-roemer** [comment]
Closing and addressing in https://github.com/FormidableLabs/builder/issues/30
