### ISSUE TITLE
webpack-dev-server parameter --host

### ISSUE THREAD

**Issue by waynelkh** [FormidableLabs/builder-react-component#26]
How can I run webpack-dev-server bind in host 0.0.0.0, I need to develop on the remote machine.

``` bash
builder run server-dev --host 0.0.0.0
```

It's not work.

**Comment by ryan-roemer** [comment]
@waynelkh -- Builder allows overrides from your root project, so in in `ROOT/package.json:scripts`, add this override:

``` js
    "server-dev": "webpack-dev-server --port 3000 --host 0.0.0.0 --config node_modules/builder-react-component/config/webpack/demo/webpack.config.dev.js --colors --content-base demo",
```

and then `builder run server-dev` and any task that _includes_ `server-dev` will use your version.

**Comment by waynelkh** [comment]
It work! Thanks.
But, is there any better way to do that?
I think overrides the script is to unnecessary.
Maybe can use npm script to pass the parameter in `builder run server-dev -- --host 0.0.0.0`？

**Comment by ryan-roemer** [comment]
@waynelkh -- Good suggestion! Captured as https://github.com/FormidableLabs/builder-react-component/issues/27 for the feature request and closing this issue.
