### ISSUE TITLE
Add initial "prompts" to builder-support?

### ISSUE THREAD

**Issue by curiouslychase** [FormidableLabs/builder-react-component#37]
I was working on a builder archetype from scratch this morning just for kicks and giggles and my `init.js` is going to look _exactly_ like the following lines in the prompts:

https://github.com/FormidableLabs/builder-react-component/blob/master/init.js#L30-L60

This is probably getting super meta, but @ryan-roemer what do you think about having `builder-support` allow you to `init` and `init.js` with specific values?

**Comment by ryan-roemer** [comment]
Hmm... `messages` might be fine, but prompting for strings on the shell like:

``` js
/^([a-z0-9]+\-?)+$/.test(val.trim()) || "Must be lower + dash-cased string"
```

seems really likely to be error prone... ?

**Comment by ryan-roemer** [comment]
@chaseadamsio -- Actually, I think I misunderstood you: you want something to _create_ `init/*` and `init.js`?

I really can't believe I'm saying this, but I think it's most appropriate to instead do an "archetype archetype" :stuck_out_tongue:

**Comment by curiouslychase** [comment]
This is a pretty stale issue and I'm pretty sure we've addressed this, so closing. 😄
