### ISSUE TITLE
BUG: .babelrc is not explicitly pointed to everywhere, sometimes doesn't get used

### ISSUE THREAD

**Issue by exogen** [FormidableLabs/builder-react-component#4]
As @boygirl found in FormidableLabs/victory-component-boilerplate#11, using the `@Radium` syntax in the new Builder-based victory-component-boilerplate doesn't work, because Babel isn't always getting its config from our `.babelrc` and thus uses the default settings.

With decorator syntax, this uses the correct `.babelrc` and works: `builder run build-lib`

These do NOT work: `builder run build-dist` and `builder run test-frontend`

Addng `.babelrc` to `ROOT` makes it work, but we don't want to have to do that.

We need a way to pass along our `.babelrc` path to Webpack (for building `dist` and testing) and `isparta` (for coverage) – the latter probably being the most difficult as I don't think an option is exposed.

/cc @ryan-roemer @boygirl

**Comment by ryan-roemer** [comment]
Yep. Makes sense. I'm looking into this.

**Comment by exogen** [comment]
There's this outstanding pull request: babel/babel-loader#121

Note that I tried putting `.babelrc` in the root of `builder-react-component` already and that didn't work – even though babel/babel#1886 claims that `.babelrc` is resolved relative to the input file it's transpiling (if that were the case, it seemed like putting it in `builder-react-component` root should work...). EDIT: Nevermind, forgot that it's transpiling files outside of `builder-react-component`...

**Comment by exogen** [comment]
Unless we get some pull requests on some third-party projects merged, or do some kind of path trickery, it's looking to me like custom `.babelrc` paths aren't well supported enough at the moment by Babel-ecosystem libraries. We could switch to using `query` for `babel-loader`, but I think that doesn't solve `isparta` as they removed the option to pass along Babel options last I checked.

Note that Babel has a `BABEL_ENV` environment variable (which then uses a certain config in your `.babelrc`), but not an environment variable for the `.babelrc` path itself.

**Comment by ryan-roemer** [comment]
Ugh. Reading up, this comports with my evolving understanding...

@boygirl / @exogen -- Can we:
- [x] Add a section in the README.md in this archetype saying "need `ROOT/.babelrc`" and a link to this issue.
- [x] Add a `.babelrc` to formidable-react-component-boilerplate and victory-boilerplate

... in the meantime?

**Comment by exogen** [comment]
@ryan-roemer  :+1: Can do. I think we should remove `--babelrc` from this archetype too in the meantime, so it's always using the same config, otherwise stuff might get weird.

**Comment by ryan-roemer** [comment]
@exogen -- Agreed. Thanks!
