### ISSUE TITLE
Extract `util/dev.js` / prod/dev dependencies Archetype publishing

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/builder-react-component#7]
From @chaseadamsio 

If you decide to go either route, it might make sense to abstract `util/dev.js` into its own package so that anyone who wanted to create builder archetypes could just use it without having to know how to use the script or update it whenever you decide to update it...it might even make sense to make it a part of `builder` as a task, something like: `builder publish archetype` inside of a repository that would publish your archetype and the `-dev` version for you.

**Comment by curiouslychase** [comment]
@ryan-roemer What are your thoughts on this? This may be a good place for me to jump in...
